-- ============================================================
-- DOMAIN 2.2: ACCESS CONTROL (RBAC) - Hands-On Queries
-- ============================================================

-- 1. Show all roles
SHOW ROLES;

-- 2. Create role hierarchy
CREATE ROLE IF NOT EXISTS CERT_READ_ROLE COMMENT = 'Read access';
CREATE ROLE IF NOT EXISTS CERT_WRITE_ROLE COMMENT = 'Write access';
CREATE ROLE IF NOT EXISTS CERT_ANALYST_ROLE COMMENT = 'Analyst functional role';
GRANT ROLE CERT_READ_ROLE TO ROLE CERT_ANALYST_ROLE;
GRANT ROLE CERT_WRITE_ROLE TO ROLE CERT_ANALYST_ROLE;
GRANT ROLE CERT_ANALYST_ROLE TO ROLE SYSADMIN;

-- 3. Grant privileges (the access chain)
GRANT USAGE ON DATABASE CERT_STUDY_DB TO ROLE CERT_READ_ROLE;
GRANT USAGE ON SCHEMA CERT_STUDY_DB.ARCHITECTURE TO ROLE CERT_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CERT_STUDY_DB.ARCHITECTURE TO ROLE CERT_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CERT_STUDY_DB.ARCHITECTURE TO ROLE CERT_READ_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CERT_READ_ROLE;

-- 4. Test role
USE ROLE CERT_ANALYST_ROLE;
SELECT COUNT(*) FROM CERT_STUDY_DB.ARCHITECTURE.SAMPLE_DATA;
USE ROLE ACCOUNTADMIN;

-- 5. View grants
SHOW GRANTS TO ROLE CERT_READ_ROLE;
SHOW GRANTS ON DATABASE CERT_STUDY_DB;

-- 6. Database roles
CREATE DATABASE ROLE IF NOT EXISTS CERT_STUDY_DB.DB_READER;
GRANT USAGE ON SCHEMA CERT_STUDY_DB.ARCHITECTURE TO DATABASE ROLE CERT_STUDY_DB.DB_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA CERT_STUDY_DB.ARCHITECTURE TO DATABASE ROLE CERT_STUDY_DB.DB_READER;
SHOW DATABASE ROLES IN DATABASE CERT_STUDY_DB;
